config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :projects do
    resources :comments, only: [:create] do
      collection do
        get 'view_comments'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :body, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :status_updates, as: :statusable

  validates :name, presence: true

  enum :status, [ :pending, :draft, :canceled, :completed ]

  before_update :add_status_change

  def status_changes
    StatusUpdate.where(statusable_id: self.id, statusable_type: self.class.name)
  end

  def add_status_change
    if status_changed?
      description = "Changed status to #{self.status} from #{status_was} on #{Time.current.strftime('%B %d, %Y at %H:%M %p')}"
      StatusUpdate.create(statusable_id: self.id, statusable_type: self.class.name, description: description)
    end
  end
end

app/models/status_update.rb
class StatusUpdate < ApplicationRecord
  belongs_to :statusable, polymorphic: true

  validates :statusable, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_project, only: [:create, :view_comments]

  def create
    @comment = @project.comments.build(comment_params)

    if @comment.save
      redirect_to @project, notice: 'Comment was successfully added.'
    else
      @project.reload
      render 'projects/show'
    end
  end

  def view_comments
    @comments = @project.comments
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
  end

  def show
    @comment = Comment.new
    @comments = @project.comments
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/view_comments.html.erb
<% if @comments.present? %>
  <section class="block m-auto w-100 max-w-[1200px] mt-5">
    <div class="container">
      <div class="row">
        <h1 class="font-extrabold text-center mt-10 mb-4 text-[30px]">Comments</h1>
        <div class="card m-12 ml-0 mr-0">
          <div class="card-body">
            <div class="row">
              <p>
                <table class="table-fixed Air-Pollution w-[1200px] m-auto ">
                  <thead class="bg-gray-100">
                    <tr>
                      <th class="px-4 py-2 text-left" scope="col">Email</th>
                      <th class="px-4 py-2 text-left" scope="col">Comment</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @comments.each do |comment| %>
                      <tr>
                        <td class="border px-4 py-2"><%= comment.user.email %></td>
                        <td class="border px-4 py-2"><%= comment.body %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <h1 class="text-center text-lg mt-10">No comments available.</h1>
<% end %>

app/views/home/index.html.erb
<h1 class="font-extrabold text-center mt-10 text-[30px]">Welcome</h1>

app/views/layouts/_navbar.html.erb
 <nav class="flex items-center justify-between flex-wrap shadow-sm p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <span class="font-semibold text-xl tracking-tight text-black font-bold text-[20px]">Project Conversation</span>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow ml-10">
      <a href="/" class="block mt-4 lg:inline-block lg:mt-0  hover:text-teal-500 mr-10 font-semibold text-lg">
        Home
      </a>
        <%= link_to 'Add project', new_project_path, method: :get, class: 'block mt-4 lg:inline-block lg:mt-0 hover:text-teal-500 mr-10  font-semibold text-lg' %>  
        <%= link_to 'View projects', projects_path, method: :get, class: 'block mt-4 lg:inline-block lg:mt-0 hover:text-teal-500  font-semibold text-lg' %> 
    </div>
    <div>
      <ul class="navbar-nav flex items-center">
        <% if user_signed_in? %>
          <li class="nav-item nav-link  font-semibold text-lg">
          <%=" #{current_user.email}"%>
          </li>
          <li class="nav-item ml-5">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'inline-block text-sm px-4 py-2 leading-none border rounded text-white bg-teal-500 border-teal-500 hover:border-teal-500 hover:text-white hover:bg-teal-700 mt-4 lg:mt-0 signoutBTN' %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item ">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link  btn-primary' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversationHistory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'wind', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' %> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="w-full max-w-[500px] m-auto mt-10 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <%= form_with(model: @project, local: true) do |form| %>
    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
        <%= form.label :name, { class: "form-label"} %>
      </label>

      <%= form.text_field :name, { class: "form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-3", placeholder: "Project Name" } %>
    </div>
    <div class="mb-8">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="username"> 
      <%= form.label :status, { class: "form-label"} %>
      </label>
      <div class="form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-3">
         <%= form.select :status, options_for_select(Project.statuses.map { |key, value| 
         [key.capitalize, key]}, @project.status) %>
       </div>
    </div>
    <div class="flex items-center justify-end">
      <button class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button">
        <%= form.submit "#{@project.id ? 'Update' : 'Create'}", class: "btn btn-primary" %>
      </button>

      <%= link_to 'Back', projects_path, class: 'bg-gray-300 pt-2 pb-2 p-5 rounded-md text-black ml-3' %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1 class="font-extrabold text-center mt-10 mb-0 text-[30px]">Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1 class="font-extrabold text-center mt-10 mb-0 text-[30px]">My Projects</h1>

<section class="block m-auto w-100">
  <div class="container">
    <div class="row">
      <div class="card m-12">
        <div class="card-body">
          <div class="row">
              <p>
                <table class="table-fixed Air-Pollution w-[1200px] m-auto ">
                  <thead class="bg-gray-100">
                    <tr>
                      <th class="px-4 py-2 text-left" scope="col">Name</th>
                      <th class="px-4 py-2 text-left" scope="col">Status</th>
                      <th class="px-4 py-2"></th>
                      <th class="px-4 py-2"></th>
                      <th class="px-4 py-2"></th>
                      <th class="px-4 py-2"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @projects.each do |project| %>
                      <tr>
                        <td class="border px-4 py-2"><%= project.name %></td>
                        <td class="border px-4 py-2"><%= project.status %></td>
                        <td class="border px-4 py-2"><%= link_to 'View Project', project_path(project.id), method: :get, class: 'text-teal-500' %></td>
                        <td class="border px-4 py-2"><%= link_to 'Edit Project', edit_project_path(project.id), method: :get, class: 'text-teal-500' %></td>
                        <td class="border px-4 py-2"><%= link_to 'Show comments', view_comments_project_comments_path(project.id), method: :get, class: 'text-teal-500' %></td>
                        <td class="border px-4 py-2">
                          <%= button_to 'Delete', project_path(project), method: :delete, class: 'btn-primary delete-btn text-teal-500' %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/new.html.erb
<h1 class="font-extrabold text-center mt-10 text-[30px]">New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="w-full max-w-[1200px] m-auto mt-10">
  <h1 class="text-xl mb-3">
    <Strong>Project Name:</Strong>  
    <span class="text-[16px]"><%= @project.name %></span>
  </h1>

  <p class="text-xl mb-3"><Strong>Status: </Strong>
    <span class="text-[16px]">
      <%= @project.status %>
    </span>
  </p>

  <% if @project.status_changes.present? %>
    <h2 class="text-xl mb-3"><Strong>Project Status Changes</Strong></h2>
    <% @project.status_changes.each do |status_change| %>
      <p  class="text-[16px]">
        <%= status_change.description %>
      </p>
    <% end %>
  <% end %>

  <h2  class="text-xl mb-3 font-bold mt-3">Add Comment</h2>
  <%= form_with(model: [@project, @comment], url: project_comments_path(@project), local: true) do |form| %>
    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
        <%= form.label :body %>
      </label>
      <%= form.text_area :body, rows: 4, class: "form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-3" %>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= form.submit 'Add Comment', class: "bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>

  <% if @comments.present? %>
    <h2 class="text-xl mb-3 mt-5 font-bold">Comments</h2>

    <table class="table-fixed Air-Pollution w-[1200px] m-auto ">
      <thead class="bg-gray-100">
        <tr>
          <th class="px-4 py-2 text-left" scope="col">Email</th>
          <th class="px-4 py-2 text-left" scope="col">Comment</th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td class="border px-4 py-2"><%= comment.user.email %></td>
            <td class="border px-4 py-2"><%= comment.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>